### ISSUE TITLE
TypeError: mainEle is undefined

### ISSUE THREAD

**Issue by pdehaan** [biancadanforth/tracking-protection-shield-study#135]
Not sure why I'm seeing this in my Browser Console on latest Nightly...

`TypeError: mainEle is undefined` in [new-tab-variation.js:97:13]

https://github.com/biancadanforth/tracking-protection-shield-study/blob/43024167b1b0eb576d487a498053e9e353116c17/addon/content/new-tab-variation.js#L95-L99

If I dig through the DevTools DOM Inspector, I can see a `<main>` element. Maybe it's just a timing issue.

![firefox_nightly](https://user-images.githubusercontent.com/557895/37007441-2df95d20-2092-11e8-98ba-aa9728b8146d.png)

**Comment by biancadanforth** [comment]
I'm going to guess this was a symptom of #132 , where I was indiscriminately adding the newtab mod to every page. If the page didn't have a `<main>` element, it'd probably throw that error. I don't see that it's possible to get that error from an actual `about:newtab` page, since I don't call this method until after the page loads (and therefore the DOM is accessible).

What I can do, just to be safe is to handle the case where `<main>` is not there.
