### ISSUE TITLE
"new-tab-closed" event is fired twice after opening a tab and navigating to a website

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [biancadanforth/tracking-protection-shield-study#159]
[Affected versions]:
- Unbranded Beta 59.0b14

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a firefox profile with QA Helper addon installed before installing study.
- Have the latest Tracking Protection Messaging .xpi installed (v.1.0.1)

[Steps to reproduce]:
- Open the browser with the profile from prerequisites.
- Open a new tab and navigate on a website.

[Expected result]:
- One ping of the "new-tab-closed" event is fired.

[Actual result]:
- Two pings of the same "new-tab-closed" event are fired.

[Notes]:
- The issue si reproducible with both branches "fast" or "private".
- Attached a screen recording of the issue:
![dubplicate_new-tab-closed](https://user-images.githubusercontent.com/20083658/37199737-32fe1c7e-238b-11e8-8065-0833ebf5a500.gif)

**Comment by biancadanforth** [comment]
Thanks Emil for finding this bug. That is odd that the new-tab-closed event is firing twice at the same time. While this would in fact add noise to our estimates for average/median open time for new tab, this metric is a relatively poor indicator of engagement, since there are many reasons the user would visit the new tab page and we have no way of knowing if they actually see the study message when they do visit, since there is no interactive portion of that modification.

@gregglind, I am thinking this is a P2, possibly a P3. What do you think?

**Comment by biancadanforth** [comment]
@SoftVision-CarmenFat To answer the question from your e-mail:
> The "new-tab-closed" event is fired after opening a tab and navigating to a website, shouldn't be named "new-tab-open" instead?

I can see how this would sound confusing! What I am referring to when the `new-tab-closed` ping happens is when the `about:newtab` page is closed, not the tab itself. I hope to have the `TELEMETRY.md` document updated soon (another team member is writing that), so hopefully that will help illuminate better what each of the pings is meant to record. For now, please do ask in the related issue (or over e-mail)

**Comment by gregglind** [comment]
P2.  `about:newtab` is weird on a first window, I think. 

I feel like SOMEONE should see this and explain why it's obvious.

(Claim in the old days: there was a brief 'secret' about:newtab instance).

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible with the latest Tracking Protection Messaging .xpi installed (v.1.0.2), retested on Windows 10 x64, Mac OS 10.12 and Ubuntu 16.04 with Unbranded Beta 59.0b14.
