### ISSUE TITLE
"Tracking Protection" tooltip is displayed when elements from the panels are hovered

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [biancadanforth/tracking-protection-shield-study#189]
[Affected versions]:
- Unbranded Beta 59.0b14

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have the latest Tracking Protection Messaging .xpi installed (v.1.0.6)

[Steps to reproduce]:
1. Open the browser and navigate to a website (e.g. www.cnn.com).
2. Click the pageAction Badge.
3. Hover random elements from the panel and observe the behavior.

[Expected result]:
- Nothing happens, there is no tooltip displayed.

[Actual result]:
- "Tracking Protection" tooltip is displayed.

[Notes]:
- This is also reproducible with Intro panel.
- This is reproducible on both "fast" and "private" variants.
- Attached a screen recording of this: 

![tooltip everywhere](https://user-images.githubusercontent.com/26000308/37466979-b3af9b78-2867-11e8-86f9-ff45c045cd8d.gif)

**Comment by biancadanforth** [comment]
Okay thanks Carmen; I'll just revert the tooltip for now. XUL elements are weird. In future, I could probably change how I implement the panel so it's not a child element of the pageAction button. I can't control the behavior of when the tooltip shows outside of that, since it's a XUL attribute on the pageAction `<toolbarbutton>` element.
