### ISSUE TITLE
"URL is not a constructor" error when study ends while page loading

### ISSUE THREAD

**Issue by biancadanforth** [biancadanforth/tracking-protection-shield-study#51]
Even though the addon has executed its shutdown method (including `feature.uninit` which removes the `WebRequest.onBeforeRequest` listener, and unloading Feature.jsm), if I end the study via the intro panel while a page is still loading, I get a bunch of `"URL is not a constructor"` errors in the browser console from Feature.jsm.

![screen shot 2018-01-21 at 7 51 39 pm](https://user-images.githubusercontent.com/17437436/35204662-87a2801a-fee4-11e7-91b2-532da3514241.png)

The line the error references is from the `onBeforeRequest` event handler method, which shouldn't be firing anymore.

```javascript
const host = new URL(details.originUrl).host;
```

When I click the link to Feature.jsm in the browser console, it takes me to a blank page, since the module is unloaded.

What on earth is going on? @rhelmer , any ideas?

**Comment by biancadanforth** [comment]
@gregglind Can you take a look at this one?

**Comment by gregglind** [comment]
```
      if (!currentURI) {
        return {};
      }

      // the URL for the entity making the request
      if (!details.originUrl) {
        return {};
      }

      if (currentURI.scheme !== "http" && currentURI.scheme !== "https") {
        return {};
      }
```

Claim:  
- this is happening during a death race, and we need to guard inside
- 1.  add comments to each of those 'ifs' saying why / when they happen or that to ask rhelmer
- 2.  add a new block `/* during a deathrace, URL is gone */  if (!URL) { return {} }`
- 3.  Tidyness:  future add a `const DONTBLOCKREQUEST = {}` and return that instead of new pojos'
